version: '3.4'
services:
  notebook:
    build: .
    ports:
      - "${JUPYTER_PORT:-8888}:8888"  
    environment:
      - "JUPYTER_PASSWORD=${JUPYTER_PASSWORD:-simple}"
    volumes:
      - .:/src/528_project
